name: "[flutter] E2E Test Nativebrik SDK"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "ci/fix-e2e-flutter"



jobs:
  publish-flutter-ios-e2e-app:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Install iOS
        run: xcode-select -p

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8

      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager
      - name: Build iOS
        working-directory: flutter/nativebrik_bridge/e2e
        run: flutter build ios --simulator

      - name: Zip app
        working-directory: flutter/nativebrik_bridge/e2e
        run: |
          cd build/ios/iphonesimulator && zip -r Runner.app.zip ./Runner.app

      - name: Upload to MagicPod
        working-directory: flutter/nativebrik_bridge/e2e
        run: |
          curl -L -X POST \
            -F "file=@build/ios/iphonesimulator/Runner.app.zip" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik-Flutter/upload-file/"

  publish-android-e2e-app:
    runs-on: ubuntu-latest
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager
      - name: Build iOS
        working-directory: flutter/nativebrik_bridge/e2e
        run: flutter build apk --debug

      - name: Upload e2e app
        working-directory: flutter/nativebrik_bridge/e2e
        run: |
          curl -L -X POST \
            -F "file=@build/app/outputs/flutter-apk/app-debug.apk" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik-Flutter/upload-file/"
