name: "[ios] Publish Nativebrik SDK"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: macos-13
    environment:
      name: Only Main
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: checkout
      uses: actions/checkout@v3
    - name: publish to cocoapods
      run: pod trunk push --verbose Nativebrik.podspec
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}