name: "Publish Nativebrik SDK to MagicPod"
on:
  push:
    branches: [ main ]

jobs:
  publish-ios-e2e:
    runs-on: macos-13
    environment:
      name: Only Main
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Nativebrik E2E
      run: xcodebuild -workspace ./ios/nativebrik.xcworkspace -scheme E2E -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' -derivedDataPath ./.dist
    - name: Zip app
      run: |
        cd .dist/Build/Products/Release-iphonesimulator/ && zip -r E2E.app.zip ./E2E.app
    - name: Uploade to magicpod
      run: |
        curl -L -X POST -F "file=@.dist/Build/Products/Release-iphonesimulator/E2E.app.zip" -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik/upload-file/"
  publish-android-e2e:
    runs-on: ubuntu-latest
    environment:
      name: Only Main
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Nativebrik E2E
      working-directory: android
      run: ./gradlew assemble
    - name: Zip app
      working-directory: android
      run: |
        cd ./e2e/build/outputs/apk/release/ && zip -r E2E.apk.zip ./e2e-release-unsigned.apk
    - name: Uploade to magicpod
      working-directory: android
      run: |
        curl -L -X POST -F "file=@./e2e/build/outputs/apk/release/E2E.apk.zip" -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" "https://app.magicpod.com/api/v1.0/Nativebrik.inc/Nativebrik/upload-file/"
