on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: gem install cocoapods
      - name: Release
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings Nativebrik.podspec
