name: Test
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/e2e.yaml
  pull_request:
    branches: [main]
    paths-ignore:
      - .github/workflows/e2e.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26
    strategy:
      matrix:
        scheme: [Nativebrik]
        destination: ["platform=iOS Simulator,name=iPhone 17,OS=26.0"]
    steps:
      - name: Install xcbeautify
        run: brew install xcbeautify
      # - uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: "15.4"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
        run: |
          xcodebuild test -scheme ${{ matrix.scheme }} -sdk iphonesimulator -destination '${{ matrix.destination }}' -skipMacroValidation -skipPackagePluginValidation | xcbeautify
          exit ${PIPESTATUS[0]}
