name: "[flutter] Test Nativebrik SDK"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "flutter/**"
      - .github/workflows/test-flutter.yml
  pull_request:
    branches: [ main ]
    paths:
      - "flutter/**"
      - .github/workflows/test-flutter.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.2
      - name: Validate package
        working-directory: flutter/nativebrik_bridge
        run: dart pub publish --dry-run
