name: "[android] Test Nativebrik SDK"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: '21'
      - name: unit test
        working-directory: android
        run: ./gradlew testDebugUnitTest

      - name: android test
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          working-directory: android
          api-level: 34
          target: google_apis
          arch: x86_64
          script: ./android/gradlew connectedCheck