name: Test
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/e2e.yaml
  pull_request:
    branches: [main]
    paths-ignore:
      - .github/workflows/e2e.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26
    timeout-minutes: 15
    strategy:
      matrix:
        scheme: [NubrickTests]
        destination: ["platform=iOS Simulator,name=iPhone 17,OS=26.0"]
    steps:
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
        run: |
          xcodebuild test -scheme ${{ matrix.scheme }} -sdk iphonesimulator -destination '${{ matrix.destination }}' -destination-timeout 300 -skipMacroValidation -skipPackagePluginValidation | xcbeautify
          exit ${PIPESTATUS[0]}
        env:
          COMPILER_INDEX_STORE_ENABLE: NO
