name: "[ios] Test Nativebrik SDK"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ios/**"
      - .github/workflows/test-ios.yaml
  pull_request:
    branches: [ main ]
    paths:
      - "ios/**"
      - .github/workflows/test-ios.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-14
    strategy:
      matrix:
        scheme: [
          Nativebrik
        ]
        destination: [
          'platform=iOS Simulator,name=iPhone 15,OS=17.0.1'
        ]
    steps:
      - name: Install xcbeautify
        run: brew install xcbeautify
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
        working-directory: ios
        run: |
          xcodebuild test -scheme ${{ matrix.scheme }} -sdk iphonesimulator -destination '${{ matrix.destination }}' -skipMacroValidation -skipPackagePluginValidation | xcbeautify
          exit ${PIPESTATUS[0]}

      - name: Pod lib lint
        run: pod lib lint
      - name: Should have the same version in podspec and sdk.swift
        run: |
          test $(cat ./Nativebrik.podspec | grep -E 's\.version\W+=' | grep -o -e '[0-9]\.[0-9]\.[0-9]') = $(cat ./ios/Sources/Nativebrik/sdk.swift | grep -E 'nativebrikSdkVersion\W+=' | grep -o -e '[0-9]\.[0-9]\.[0-9]')
