on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: XCTest
        run: xcodebuild test -project ./ios/Nativebrik/Nativebrik.xcodeproj -scheme NativebrikTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1'
