name: "[flutter] Test Nativebrik SDK"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "flutter/**"
      - .github/workflows/test-flutter.yaml
  pull_request:
    branches: [ main ]
    paths:
      - "flutter/**"
      - .github/workflows/test-flutter.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.2

      - name: Validate package
        working-directory: flutter/nativebrik_bridge
        run: dart pub publish --dry-run
